const products = [
  // ── MOBILES ──────────────────────────────────────────
  {
    name: 'Samsung Galaxy S24 Ultra 5G (12GB RAM, 256GB)',
    description: 'Galaxy AI is here. Welcome to the era of mobile AI. With Galaxy S24 Ultra, you can unleash whole new levels of creativity, productivity and possibility. Built-in S Pen, 200MP camera, Titanium frame.',
    price: 129999,
    originalPrice: 144999,
    discountPercent: 10,
    rating: 4.8,
    numReviews: 1420,
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&q=80',
    images: ['https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&q=80'],
    category: 'Mobiles',
    stock: 25,
    specifications: { 'RAM': '12 GB', 'Storage': '256 GB', 'Camera': '200MP + 50MP + 12MP', 'Processor': 'Snapdragon 8 Gen 3' },
  },
  {
    name: 'Apple iPhone 15 Pro (128 GB) - Natural Titanium',
    description: 'Forged in titanium. Featuring the groundbreaking A17 Pro chip, a customizable Action button, and the most powerful iPhone camera system ever.',
    price: 134900,
    originalPrice: 139900,
    discountPercent: 4,
    rating: 4.9,
    numReviews: 2150,
    image: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&q=80',
    category: 'Mobiles',
    stock: 30,
    specifications: { 'Chip': 'A17 Pro', 'Display': '6.1-inch Super Retina XDR', 'Camera': '48MP Main' },
  },
  {
    name: 'Redmi Note 13 Pro+ 5G (8GB RAM, 256GB Storage)',
    description: 'World-first 200MP camera with OIS, 3D Curved AMOLED display, 120W HyperCharge, IP68 dust and water resistance.',
    price: 31999,
    originalPrice: 37999,
    discountPercent: 16,
    rating: 4.5,
    numReviews: 890,
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&q=80',
    category: 'Mobiles',
    stock: 50,
    specifications: { 'RAM': '8 GB', 'Storage': '256 GB', 'Charging': '120W HyperCharge' },
  },
  {
    name: 'OnePlus 12 5G (16GB RAM, 512GB Storage)',
    description: 'Smooth Beyond Belief. Snapdragon 8 Gen 3, 4th Gen Hasselblad Camera System for Mobile, 2K 120 Hz ProXDR Display, 100W SUPERVOOC.',
    price: 69999,
    originalPrice: 74999,
    discountPercent: 7,
    rating: 4.7,
    numReviews: 640,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=80',
    category: 'Mobiles',
    stock: 20,
    specifications: { 'RAM': '16 GB', 'Camera': 'Hasselblad 50MP', 'Battery': '5400 mAh' },
  },
  {
    name: 'Realme 12 Pro+ 5G (8GB RAM, 128GB Storage)',
    description: '64MP Periscope Portrait Camera, Snapdragon 7s Gen 2, 120Hz Curved Vision Display, Luxury Watch Design.',
    price: 29999,
    originalPrice: 34999,
    discountPercent: 14,
    rating: 4.4,
    numReviews: 430,
    image: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=600&q=80',
    category: 'Mobiles',
    stock: 40,
    specifications: { 'Camera': '64MP Periscope', 'Display': '120Hz Curved AMOLED' },
  },

  // ── ELECTRONICS ──────────────────────────────────────
  {
    name: 'Sony WH-1000XM5 Wireless Noise Canceling Headphones',
    description: 'Industry-leading noise cancellation with 8 microphones and Auto NC Optimizer. Magnificently engineered for sound quality.',
    price: 29990,
    originalPrice: 34990,
    discountPercent: 14,
    rating: 4.9,
    numReviews: 3240,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80',
    category: 'Electronics',
    stock: 35,
    specifications: { 'Battery': '30 Hours', 'Noise Cancellation': 'Industry Leading HD V1' },
  },
  {
    name: 'Apple AirPods Pro (2nd Generation) with MagSafe Case',
    description: 'Active Noise Cancellation reduces unwanted background noise. Adaptive Transparency lets outside sounds in while reducing loud environmental noise.',
    price: 22900,
    originalPrice: 24900,
    discountPercent: 8,
    rating: 4.8,
    numReviews: 4890,
    image: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=600&q=80',
    category: 'Electronics',
    stock: 45,
    specifications: { 'Chip': 'Apple H2', 'Audio': 'Personalized Spatial Audio' },
  },
  {
    name: 'boAt Airdopes 141 Bluetooth TWS Earbuds',
    description: 'Enjoy an immersive audio experience with 42H playback, Beast Mode for gaming, ENx Tech for clear calls, and ASAP Charge.',
    price: 1299,
    originalPrice: 4490,
    discountPercent: 71,
    rating: 4.2,
    numReviews: 12400,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&q=80',
    category: 'Electronics',
    stock: 120,
    specifications: { 'Playback': '42 Hours', 'Drivers': '8mm Dynamic' },
  },
  {
    name: 'JBL Flip 6 Portable Bluetooth Speaker (20W RMS output)',
    description: 'Louder, more powerful sound. IP67 waterproof and dustproof. 12 hours of playtime. PartyBoost feature.',
    price: 9999,
    originalPrice: 13999,
    discountPercent: 28,
    rating: 4.7,
    numReviews: 1850,
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&q=80',
    category: 'Electronics',
    stock: 30,
    specifications: { 'Output': '20W RMS', 'Waterproof': 'IP67 Rated' },
  },
  {
    name: 'Logitech MX Master 3S Performance Wireless Mouse',
    description: 'Quiet Clicks, 8K DPI Any-Surface Tracking, Ergonomic, Quiet Scroll Wheel, USB-C, Bluetooth, Windows/Mac.',
    price: 8995,
    originalPrice: 10995,
    discountPercent: 18,
    rating: 4.8,
    numReviews: 950,
    image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&q=80',
    category: 'Electronics',
    stock: 25,
    specifications: { 'DPI': '8000 DPI', 'Connectivity': 'Bluetooth + Logi Bolt' },
  },

  // ── COMPUTERS & LAPTOPS ──────────────────────────────
  {
    name: 'Apple MacBook Air 15" M3 Chip (8GB RAM, 256GB SSD)',
    description: 'Incredibly thin and fast laptop with up to 18 hours of battery life, Liquid Retina display, 1080p FaceTime HD camera.',
    price: 134900,
    originalPrice: 139900,
    discountPercent: 4,
    rating: 4.9,
    numReviews: 780,
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=80',
    category: 'Computers & Laptops',
    stock: 15,
    specifications: { 'CPU': 'Apple M3 8-Core', 'RAM': '8GB Unified', 'SSD': '256GB' },
  },
  {
    name: 'ASUS ROG Strix G16 Gaming Laptop (Intel i7-13650HX, RTX 4060)',
    description: 'Power your play with Windows 11 Home, 13th Gen Intel Core i7 processor, and NVIDIA GeForce RTX 4060 Laptop GPU.',
    price: 139990,
    originalPrice: 169990,
    discountPercent: 18,
    rating: 4.7,
    numReviews: 310,
    image: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&q=80',
    category: 'Computers & Laptops',
    stock: 10,
    specifications: { 'GPU': 'NVIDIA RTX 4060 8GB', 'RAM': '16GB DDR5', 'Display': '16" 165Hz FHD+' },
  },
  {
    name: 'HP Pavilion 15 (13th Gen Intel Core i5, 16GB RAM, 512GB SSD)',
    description: 'FHD IPS Micro-Edge Display, Iris Xe Graphics, Backlit KB, B&O Audio, Windows 11, MS Office 2021.',
    price: 64990,
    originalPrice: 77990,
    discountPercent: 17,
    rating: 4.4,
    numReviews: 1290,
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=80',
    category: 'Computers & Laptops',
    stock: 40,
    specifications: { 'Processor': 'Intel Core i5-1335U', 'RAM': '16 GB', 'SSD': '512 GB' },
  },
  {
    name: 'Apple iPad Air (5th Gen, M1 Chip, 64GB, Wi-Fi)',
    description: '10.9-inch Liquid Retina display with True Tone, P3 wide color, and an anti-reflective coating. M1 chip with Neural Engine.',
    price: 54900,
    originalPrice: 59900,
    discountPercent: 8,
    rating: 4.8,
    numReviews: 1650,
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&q=80',
    category: 'Computers & Laptops',
    stock: 25,
    specifications: { 'Chip': 'Apple M1', 'Display': '10.9-inch Liquid Retina' },
  },

  // ── TV & APPLIANCES ──────────────────────────────────
  {
    name: 'Samsung 55 Inches 4K Ultra HD Smart QLED TV',
    description: 'Quantum Dot technology delivers 100% Color Volume. Quantum Processor 4K, Motion Xcelerator Turbo+, Q-Symphony.',
    price: 64990,
    originalPrice: 99900,
    discountPercent: 35,
    rating: 4.7,
    numReviews: 890,
    image: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=600&q=80',
    category: 'TV & Appliances',
    stock: 18,
    specifications: { 'Screen': '55 Inch QLED', 'Resolution': '4K Ultra HD', 'Refresh Rate': '120Hz' },
  },
  {
    name: 'LG 43 Inches 4K Ultra HD Smart LED TV',
    description: 'α5 AI Processor 4K Gen6, WebOS 23, Magic Remote, Unlimited OTT Apps, Game Optimizer.',
    price: 31990,
    originalPrice: 49990,
    discountPercent: 36,
    rating: 4.5,
    numReviews: 2400,
    image: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=600&q=80',
    category: 'TV & Appliances',
    stock: 35,
    specifications: { 'Screen': '43 Inch 4K', 'OS': 'WebOS 23' },
  },
  {
    name: 'Voltas 1.5 Ton 5 Star Inverter Split AC',
    description: 'Copper Condenser, 6 in 1 Adjustable Cooling, Anti Dust Filter, 2024 Model, White.',
    price: 37990,
    originalPrice: 75990,
    discountPercent: 50,
    rating: 4.3,
    numReviews: 1800,
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&q=80',
    category: 'TV & Appliances',
    stock: 20,
    specifications: { 'Capacity': '1.5 Ton', 'Energy Rating': '5 Star Inverter' },
  },
  {
    name: 'Whirlpool 265 L 3 Star Frost Free Double Door Refrigerator',
    description: 'IntelliSense Inverter Technology, Zeolite Technology keeps fruits and vegetables fresh for up to 15 days.',
    price: 27490,
    originalPrice: 35650,
    discountPercent: 23,
    rating: 4.4,
    numReviews: 1540,
    image: 'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=600&q=80',
    category: 'TV & Appliances',
    stock: 15,
    specifications: { 'Capacity': '265 Litres', 'Type': 'Frost Free Double Door' },
  },

  // ── MEN'S FASHION ────────────────────────────────────
  {
    name: 'Levi\'s Men 501 Original Fit Jeans',
    description: 'The iconic 501 straight fit jeans. Made from 100% durable cotton denim with signature button fly.',
    price: 3299,
    originalPrice: 4599,
    discountPercent: 28,
    rating: 4.6,
    numReviews: 1120,
    image: 'https://images.unsplash.com/photo-1542272454315-4c01d7abdf4a?w=600&q=80',
    category: 'Men\'s Fashion',
    stock: 60,
    specifications: { 'Fit': 'Straight Fit', 'Fabric': '100% Cotton Denim' },
  },
  {
    name: 'U.S. POLO ASSN. Men Solid Regular Fit Polo T-Shirt',
    description: 'Classic polo t-shirt with embroidered brand logo. Premium breathable cotton fabric for maximum comfort.',
    price: 1299,
    originalPrice: 2199,
    discountPercent: 41,
    rating: 4.4,
    numReviews: 3400,
    image: 'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=600&q=80',
    category: 'Men\'s Fashion',
    stock: 90,
    specifications: { 'Fit': 'Regular Fit', 'Sleeve': 'Short Sleeves' },
  },
  {
    name: 'Allen Solly Men Slim Fit Formal Blazer',
    description: 'Single-breasted 2-button formal blazer crafted from premium poly-viscose blend for wedding and office wear.',
    price: 4999,
    originalPrice: 8999,
    discountPercent: 44,
    rating: 4.5,
    numReviews: 540,
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&q=80',
    category: 'Men\'s Fashion',
    stock: 30,
    specifications: { 'Pattern': 'Solid', 'Occasion': 'Formal / Party' },
  },

  // ── WOMEN'S FASHION ──────────────────────────────────
  {
    name: 'BIBA Women Printed Anarkali Kurta & Dupatta Set',
    description: 'Elegant cotton Anarkali suit set with intricate ethnic print and matching printed dupatta.',
    price: 2999,
    originalPrice: 5995,
    discountPercent: 50,
    rating: 4.6,
    numReviews: 1890,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&q=80',
    category: 'Women\'s Fashion',
    stock: 45,
    specifications: { 'Fabric': '100% Pure Cotton', 'Style': 'Anarkali' },
  },
  {
    name: 'Zara Women Floral Print Midi Dress',
    description: 'V-neck midi dress featuring short sleeves, elastic waist, and flared hemline. Perfect for summer outings.',
    price: 3590,
    originalPrice: 4990,
    discountPercent: 28,
    rating: 4.7,
    numReviews: 760,
    image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&q=80',
    category: 'Women\'s Fashion',
    stock: 35,
    specifications: { 'Length': 'Midi', 'Pattern': 'Floral Print' },
  },

  // ── FOOTWEAR ─────────────────────────────────────────
  {
    name: 'Nike Air Max 270 Men\'s Running Shoes',
    description: 'Boasts Nike\'s biggest heel Air unit yet for a super-soft ride that feels as impossible as it looks.',
    price: 11495,
    originalPrice: 13995,
    discountPercent: 18,
    rating: 4.7,
    numReviews: 2840,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
    category: 'Footwear',
    stock: 50,
    specifications: { 'Type': 'Running / Casual', 'Closure': 'Lace-Up' },
  },
  {
    name: 'Adidas Ultraboost 1.0 Unisex Sneakers',
    description: 'adidas PRIMEKNIT upper hugs the foot with a supportive fit. BOOST midsole delivers unbelievable energy return.',
    price: 14399,
    originalPrice: 17999,
    discountPercent: 20,
    rating: 4.8,
    numReviews: 1450,
    image: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=600&q=80',
    category: 'Footwear',
    stock: 30,
    specifications: { 'Midsole': 'Boost Technology', 'Sole': 'Rubber' },
  },
  {
    name: 'Red Tape Men\'s Leather Formal Shoes',
    description: 'Genuine leather derby formal shoes with cushioned footbed and TPR sole for office elegance.',
    price: 1899,
    originalPrice: 5999,
    discountPercent: 68,
    rating: 4.3,
    numReviews: 6200,
    image: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=600&q=80',
    category: 'Footwear',
    stock: 80,
    specifications: { 'Material': 'Genuine Leather', 'Color': 'Black' },
  },

  // ── BEAUTY & PERSONAL CARE ───────────────────────────
  {
    name: 'Lakme Absolute Matte Melt Liquid Lip Color (6ml)',
    description: 'Intense matte color that feels weightless and lasts up to 16 hours without smudging or drying lips.',
    price: 525,
    originalPrice: 800,
    discountPercent: 34,
    rating: 4.5,
    numReviews: 3890,
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600&q=80',
    category: 'Beauty',
    stock: 100,
    specifications: { 'Finish': 'Matte', 'Volume': '6ml' },
  },
  {
    name: 'Philips Norelco Beard Trimmer BT3211/15',
    description: 'Lift & Trim system cuts 30% faster. Stainless steel blades for long-lasting sharpness. 60 min cordless run time.',
    price: 1499,
    originalPrice: 1895,
    discountPercent: 21,
    rating: 4.6,
    numReviews: 14500,
    image: 'https://images.unsplash.com/photo-1621607512214-68297480165e?w=600&q=80',
    category: 'Personal Care',
    stock: 75,
    specifications: { 'Run Time': '60 Minutes', 'Blade Material': 'Stainless Steel' },
  },

  // ── HOME & KITCHEN ───────────────────────────────────
  {
    name: 'Instant Pot Duo 7-in-1 Electric Pressure Cooker (6 Litres)',
    description: 'Replaces 7 kitchen appliances: pressure cooker, slow cooker, rice cooker, steamer, sauté pan, yogurt maker and warmer.',
    price: 8999,
    originalPrice: 12999,
    discountPercent: 30,
    rating: 4.8,
    numReviews: 4500,
    image: 'https://images.unsplash.com/photo-1585515320310-259814833e62?w=600&q=80',
    category: 'Home & Kitchen',
    stock: 35,
    specifications: { 'Capacity': '6 Litres', 'Wattage': '1000W' },
  },
  {
    name: 'Prestige Svachh Hard Anodised Pressure Cooker 3L',
    description: 'Unique Spill Control Lid ensures no messy overflow. Durable hard anodised body with metallic safety plug.',
    price: 1749,
    originalPrice: 2490,
    discountPercent: 30,
    rating: 4.5,
    numReviews: 8900,
    image: 'https://images.unsplash.com/photo-1544233726-9f1d2b27be8b?w=600&q=80',
    category: 'Home & Kitchen',
    stock: 60,
    specifications: { 'Capacity': '3 Litres', 'Material': 'Hard Anodised Aluminium' },
  },

  // ── GROCERY ──────────────────────────────────────────
  {
    name: 'Fortune Sunlite Sunflower Oil Pouch, 5 Litres',
    description: 'Light and healthy sunflower oil rich in Vitamin E. Ideal for everyday cooking and deep frying.',
    price: 685,
    originalPrice: 850,
    discountPercent: 19,
    rating: 4.6,
    numReviews: 11200,
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&q=80',
    category: 'Grocery',
    stock: 150,
    specifications: { 'Volume': '5 Litres', 'Type': 'Refined Sunflower Oil' },
  },
  {
    name: 'India Gate Basmati Rice Feast Rozzana, 5kg',
    description: 'Aromatic long-grain basmati rice aged to perfection. Perfect for daily meals, biryani, and pulao.',
    price: 499,
    originalPrice: 650,
    discountPercent: 23,
    rating: 4.7,
    numReviews: 9400,
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&q=80',
    category: 'Grocery',
    stock: 200,
    specifications: { 'Weight': '5 kg', 'Grain': 'Aged Basmati Rice' },
  },

  // ── SPORTS & FITNESS ─────────────────────────────────
  {
    name: 'Decathlon Yoga & Fitness Mat 6mm Non-Slip',
    description: 'Extra thick 6mm cushioning protects joints during yoga, pilates and workouts. Includes carrying strap.',
    price: 899,
    originalPrice: 1499,
    discountPercent: 40,
    rating: 4.7,
    numReviews: 2100,
    image: 'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=600&q=80',
    category: 'Sports & Fitness',
    stock: 80,
    specifications: { 'Thickness': '6mm', 'Material': 'TPE Non-slip' },
  },
  {
    name: 'Nivia Storm Football (Size 5)',
    description: 'Rubberized stitched construction suitable for hard surfaces, grass fields, and wet weather conditions.',
    price: 499,
    originalPrice: 790,
    discountPercent: 37,
    rating: 4.3,
    numReviews: 5400,
    image: 'https://images.unsplash.com/photo-1511886929837-354d827aae26?w=600&q=80',
    category: 'Sports & Fitness',
    stock: 100,
    specifications: { 'Size': 'Size 5 Standard', 'Material': 'Rubberized' },
  },

  // ── BOOKS ────────────────────────────────────────────
  {
    name: 'Atomic Habits by James Clear (Paperback)',
    description: 'An Easy & Proven Way to Build Good Habits & Break Bad Ones. Over 10 million copies sold worldwide.',
    price: 449,
    originalPrice: 799,
    discountPercent: 44,
    rating: 4.9,
    numReviews: 45000,
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&q=80',
    category: 'Books',
    stock: 150,
    specifications: { 'Author': 'James Clear', 'Format': 'Paperback', 'Pages': '320' },
  },
  {
    name: 'The Psychology of Money by Morgan Housel',
    description: 'Timeless lessons on wealth, greed, and happiness doing well with money isn’t necessarily about what you know.',
    price: 299,
    originalPrice: 499,
    discountPercent: 40,
    rating: 4.8,
    numReviews: 28900,
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&q=80',
    category: 'Books',
    stock: 120,
    specifications: { 'Author': 'Morgan Housel', 'Format': 'Paperback' },
  },

  // ── WATCHES ──────────────────────────────────────────
  {
    name: 'Casio G-Shock GA-2100-1A1DR Octagonal Dial Watch',
    description: 'The Carbon Core Guard structure protects the module with a carbon-reinforced resin case. Shock resistant 200m water resistant.',
    price: 9995,
    originalPrice: 10995,
    discountPercent: 9,
    rating: 4.9,
    numReviews: 1890,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80',
    category: 'Watches',
    stock: 30,
    specifications: { 'Water Resistance': '200 Meters', 'Strap': 'Resin' },
  },
  {
    name: 'Titan Regalia Chronograph Stainless Steel Watch',
    description: 'Luxury analog quartz chronograph watch featuring a deep blue dial, date display, and stainless steel strap.',
    price: 7495,
    originalPrice: 9495,
    discountPercent: 21,
    rating: 4.6,
    numReviews: 780,
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&q=80',
    category: 'Watches',
    stock: 25,
    specifications: { 'Dial Color': 'Blue', 'Strap': 'Stainless Steel' },
  },

  // ── BAGS & LUGGAGE ───────────────────────────────────
  {
    name: 'American Tourister 79cm Polycarbonate Hard Luggage Trolley',
    description: 'Scratch-resistant textured shell, 3-digit TSA lock, 360-degree dual wheels for smooth maneuvering.',
    price: 4999,
    originalPrice: 12400,
    discountPercent: 60,
    rating: 4.6,
    numReviews: 3400,
    image: 'https://images.unsplash.com/photo-1565026057447-b8899f290583?w=600&q=80',
    category: 'Bags & Luggage',
    stock: 40,
    specifications: { 'Size': '79cm Check-In', 'Lock': 'TSA Combination' },
  },
  {
    name: 'Skybags Campus 30L Water Resistant Laptop Backpack',
    description: 'Ergonomic padded shoulder straps, 3 spacious main compartments, dedicated 15.6" laptop sleeve, rain cover.',
    price: 1199,
    originalPrice: 2800,
    discountPercent: 57,
    rating: 4.4,
    numReviews: 5600,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80',
    category: 'Bags & Luggage',
    stock: 90,
    specifications: { 'Capacity': '30 Litres', 'Laptop Compatibility': 'Up to 15.6 Inch' },
  }
];

module.exports = products;
